### PR TITLE
check trust relationships in the current domain

### PR DESCRIPTION
**Pull request by guervild**
Hey

I just added a small feature to check trust relationships in the current domain using the `--trust` flag:
```
PS C:\Tools> .\StandIn.exe --trust

[?] Using DC    : DC01.intern.dojo.local
    |_ Domain   : intern.dojo.local

[*] Source                    : intern.dojo.local
    Target                    : dojo.local
    TrustDirection            : Bidirectional
    TrustType                 : ParentChild
```

### CODE REVIEW

**Comment by FuzzySecurity** [comment]
Hey, sorry I have notifications turned off by default looks like. I will get this added to the next version or if you want to re-submit that works as well.

**Comment by guervild** [comment]
Hey! No problem !
What do you prefer ? it does not bother me to remake the merge request.
Also, i have been working on other functionalities, and have a few ideas, where can i contact you to talk about it ?

**Comment by guervild** [comment]
I updated the branch to match 1.3

**Review by FuzzySecurity — APPROVED** [review]
Looks good

**Comment by FuzzySecurity** [comment]
You can DM me on twitter if you like to discuss the other functionality you are working on 👍

**Pull request merged**
